numerator = tf1.Numerator;
denominator = tf1.Denominator;
%% Współczynniki transmitancji układu boost: P = (a*s+b)/(s^2+c*s+d) %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
a = numerator(1);      
b = numerator(2);
c = numerator(3);
d = denominator(2);
e = denominator(3);

b_2 = a;
b_1 = b;
b_0 = c;
a_1 = d;
a_0 = e;

%% Obliczenia parametrów regulatora PI %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = sqrt(-1);                                                % Jednostka urojona
syms w K_p K_i;                                              % Zdefiniowanie symboli w - pulsacja, 
                                                             % K_p - współczynnik wzmocnienia części proporcjonalnej
                                                             % K_i - współczynnik wzmocnienia części całkującej
assume([K_p,K_i,w],'real');                                  % Założenie że zdefiniowane symbole są rzeczywiste


% K_p_eq = (10^0*(10^0)^(19/20)*(-(a_0*(b_0+(-b_2+b_1*t_f)*w^2)...
% +w^2*(-b_0*(1+a_1*t_f)+(b_2-b_1*t_f)*w^2+a_1*(b_1+b_2*t_f*w^2)))...
% *cos(w*T)+w*(-(a_0-w^2)*(b_1-b_0*t_f+b_2*t_f*w^2)...
% +a_1*(b_0+(-b_2+b_1*t_f)*w^2))*sin(w*T)))/...
%     (b_0^2+b_1^2*w^2-2*b_0*b_2*w^2+b_2^2*w^4);
% 
% K_i_eq = (10^0*(10^0)^(19/20)*w*(w*(-(a_0-w^2)*(b_1-b_0*t_f+b_2*t_f*w^2)...
%     +a_1*(b_0+(-b_2+b_1*t_f)*w^2))*cos(w*T)...
%     +(a_0*(b_0+(-b_2+b_1*t_f)*w^2)+w^2*(-b_0*(1+a_1*t_f)...
%     +(b_2-b_1*t_f)*w^2+a_1*(b_1+b_2*t_f*w^2)))*sin(w*T)))/...
%     (b_0^2+b_1^2*w^2-2*b_0*b_2*w^2+b_2^2*w^4);
% 
% K_p_PM_low_eq = (cos(pi*PM_low/180)*(-(a_0*(b_0+(-b_2+b_1*t_f)*w^2)...
%     +w^2*(-b_0*(1+a_1*t_f)+(b_2-b_1*t_f)*w^2+a_1*...
%     (b_1+b_2*t_f*w^2)))*cos(w*T)+w*(-(a_0-w^2)*(b_1-...
%     b_0*t_f+b_2*t_f*w^2)+a_1*(b_0+(-b_2+b_1*t_f)*w^2))*...
%     sin(w*T))+sin(pi*PM_low/180)*(w*(-(a_0-w^2)*(b_1-...
%     b_0*t_f+b_2*t_f*w^2)+a_1*(b_0+(-b_2+b_1*t_f)*w^2))*...
%     cos(w*T)+(a_0*(b_0+(-b_2+b_1*t_f)*w^2)+w^2*...
%     (-b_0*(1+a_1*t_f)+(b_2-b_1*t_f)*w^2+a_1*(b_1+b_2*t_f*w^2)))*...
%     sin(w*T)))/...
%     (b_0^2+b_1^2*w^2-2*b_0*b_2*w^2+b_2^2*w^4);
% 
% K_p_PM_high_eq = (cos(pi*PM_high/180)*(-(a_0*(b_0+(-b_2+b_1*t_f)*w^2)...
%     +w^2*(-b_0*(1+a_1*t_f)+(b_2-b_1*t_f)*w^2+a_1*...
%     (b_1+b_2*t_f*w^2)))*cos(w*T)+w*(-(a_0-w^2)*(b_1-...
%     b_0*t_f+b_2*t_f*w^2)+a_1*(b_0+(-b_2+b_1*t_f)*w^2))*...
%     sin(w*T))+sin(pi*PM_high/180)*(w*(-(a_0-w^2)*(b_1-...
%     b_0*t_f+b_2*t_f*w^2)+a_1*(b_0+(-b_2+b_1*t_f)*w^2))*...
%     cos(w*T)+(a_0*(b_0+(-b_2+b_1*t_f)*w^2)+w^2*...
%     (-b_0*(1+a_1*t_f)+(b_2-b_1*t_f)*w^2+a_1*(b_1+b_2*t_f*w^2)))*...
%     sin(w*T)))/...
%     (b_0^2+b_1^2*w^2-2*b_0*b_2*w^2+b_2^2*w^4);
% 
%  K_i_PM_high_eq = (w*(sin(pi*PM_high/180)*((a_0*(b_0+(-b_2+...
%      b_1*t_f)*w^2)+w^2*(-b_0*(1+a_1*t_f)+(b_2-b_1*t_f)*w^2+...
%      a_1*(b_1+b_2*t_f*w^2)))*cos(w*T)-w*(-(a_0-w^2)*(b_1-b_0*t_f+...
%      b_2*t_f*w^2)+a_1*(b_0+(-b_2+b_1*t_f)*w^2))*sin(w*T))+cos(pi*PM_high/180)*...
%      (w*(-(a_0-w^2)*(b_1-b_0*t_f+b_2*t_f*w^2)+a_1*(b_0+(-b_2+...
%      b_1*t_f)*w^2))*cos(w*T)+(a_0*(b_0+(-b_2+b_1*t_f)*w^2)+...
%      w^2*(-b_0*(1+a_1*t_f)+(b_2-b_1*t_f)*w^2+a_1*(b_1+b_2*t_f*w^2)))*...
%      sin(w*T))))/...
%      (b_0^2+b_1^2*w^2-2*b_0*b_2*w^2+b_2^2*w^4);
% 
% K_i_PM_low_eq = (w*(sin(pi*PM_low/180)*((a_0*(b_0+(-b_2+...
%      b_1*t_f)*w^2)+w^2*(-b_0*(1+a_1*t_f)+(b_2-b_1*t_f)*w^2+...
%      a_1*(b_1+b_2*t_f*w^2)))*cos(w*T)-w*(-(a_0-w^2)*(b_1-b_0*t_f+...
%      b_2*t_f*w^2)+a_1*(b_0+(-b_2+b_1*t_f)*w^2))*sin(w*T))+cos(pi*PM_low/180)*...
%      (w*(-(a_0-w^2)*(b_1-b_0*t_f+b_2*t_f*w^2)+a_1*(b_0+(-b_2+...
%      b_1*t_f)*w^2))*cos(w*T)+(a_0*(b_0+(-b_2+b_1*t_f)*w^2)+...
%      w^2*(-b_0*(1+a_1*t_f)+(b_2-b_1*t_f)*w^2+a_1*(b_1+b_2*t_f*w^2)))*...
%      sin(w*T))))/...
%      (b_0^2+b_1^2*w^2-2*b_0*b_2*w^2+b_2^2*w^4);
% 
% K_p_GM_high_eq = (10^(-GM_high)*(10^GM_high)^(19/20)*(-(a_0*(b_0+(-b_2+b_1*t_f)*w^2)...
% +w^2*(-b_0*(1+a_1*t_f)+(b_2-b_1*t_f)*w^2+a_1*(b_1+b_2*t_f*w^2)))...
% *cos(w*T)+w*(-(a_0-w^2)*(b_1-b_0*t_f+b_2*t_f*w^2)...
% +a_1*(b_0+(-b_2+b_1*t_f)*w^2))*sin(w*T)))/...
%     (b_0^2+b_1^2*w^2-2*b_0*b_2*w^2+b_2^2*w^4);
% 
% K_i_GM_high_eq = (10^(-GM_high)*(10^GM_high)^(19/20)*w*(w*(-(a_0-w^2)*(b_1-b_0*t_f+b_2*t_f*w^2)...
%     +a_1*(b_0+(-b_2+b_1*t_f)*w^2))*cos(w*T)...
%     +(a_0*(b_0+(-b_2+b_1*t_f)*w^2)+w^2*(-b_0*(1+a_1*t_f)...
%     +(b_2-b_1*t_f)*w^2+a_1*(b_1+b_2*t_f*w^2)))*sin(w*T)))/...
%     (b_0^2+b_1^2*w^2-2*b_0*b_2*w^2+b_2^2*w^4);
% 
% K_p_GM_low_eq = (10^(-GM_low)*(10^GM_low)^(19/20)*(-(a_0*(b_0+(-b_2+b_1*t_f)*w^2)...
% +w^2*(-b_0*(1+a_1*t_f)+(b_2-b_1*t_f)*w^2+a_1*(b_1+b_2*t_f*w^2)))...
% *cos(w*T)+w*(-(a_0-w^2)*(b_1-b_0*t_f+b_2*t_f*w^2)...
% +a_1*(b_0+(-b_2+b_1*t_f)*w^2))*sin(w*T)))/...
%     (b_0^2+b_1^2*w^2-2*b_0*b_2*w^2+b_2^2*w^4);
% 
% K_i_GM_low_eq = (10^(-GM_low)*(10^GM_low)^(19/20)*w*(w*(-(a_0-w^2)*(b_1-b_0*t_f+b_2*t_f*w^2)...
%     +a_1*(b_0+(-b_2+b_1*t_f)*w^2))*cos(w*T)...
%     +(a_0*(b_0+(-b_2+b_1*t_f)*w^2)+w^2*(-b_0*(1+a_1*t_f)...
%     +(b_2-b_1*t_f)*w^2+a_1*(b_1+b_2*t_f*w^2)))*sin(w*T)))/...
%     (b_0^2+b_1^2*w^2-2*b_0*b_2*w^2+b_2^2*w^4);


w_list = 1:1:30000;                                          % Wektor pulsacji
K_i_list = zeros(1,length(w_list));                          % Wektor współczynnika wzmocnienia części całkującej
K_p_list = zeros(1,length(w_list));                          % Wektor współczynnika wzmocnienia części proporcjonalnej


K_i_PM_low_list = zeros(1,length(w_list));                   % Wektor współczynnika wzmocnienia części całkującej 
                                                             % dla zadanego zapasu fazy
K_p_PM_low_list = zeros(1,length(w_list));                   % Wektor współczynnika wzmocnienia części proporcjonalnej
                                                             % dla zadanego zapasu fazy
K_i_GM_low_list = zeros(1,length(w_list));                   % Wektor współczynnika wzmocnienia części całkującej 
                                                             % dla zadanego zapasu wzmocnienia
K_p_GM_low_list = zeros(1,length(w_list));                   % Wektor współczynnika wzmocnienia części proporcjonalnej
                                                             % dla zadanego zapasu wzmocnienia
                                                             
K_i_PM_high_list = zeros(1,length(w_list));                  % Wektor współczynnika wzmocnienia części całkującej 
                                                             % dla zadanego zapasu fazy
K_p_PM_high_list = zeros(1,length(w_list));                  % Wektor współczynnika wzmocnienia części proporcjonalnej
                                                             % dla zadanego zapasu fazy
K_i_GM_high_list = zeros(1,length(w_list));                  % Wektor współczynnika wzmocnienia części całkującej 
                                                             % dla zadanego zapasu wzmocnienia
K_p_GM_high_list = zeros(1,length(w_list));                  % Wektor współczynnika wzmocnienia części proporcjonalnej
k1 = 1;                                                             % dla zadanego zapasu wzmocnienia
k2 = 1;
k3 = 1;
k4 = 1;
k5 = 1;
k6 = 1;
for k = 1:length(w_list)                                     % Obliczenia wartości wektorów 
                                                             % współczynników regulatora PI
%      K_p_list(k) = eval(subs(K_p_eq,w,w_list(k)));
%      K_i_list(k) = eval(subs(K_i_eq,w,w_list(k)));
%      K_p_PM_low_list(k) = eval(subs(K_p_PM_low_eq,w,w_list(k)));
%      K_i_PM_low_list(k) = eval(subs(K_i_PM_low_eq,w,w_list(k)));
%      K_p_GM_low_list(k) = eval(subs(K_p_GM_low_eq,w,w_list(k)));
%      K_i_GM_low_list(k) = eval(subs(K_i_GM_low_eq,w,w_list(k)));
%      K_p_GM_high_list(k) = eval(subs(K_p_GM_high_eq,w,w_list(k)));
%      K_i_GM_high_list(k) = eval(subs(K_i_GM_high_eq,w,w_list(k)));
%      K_p_PM_high_list(k) = eval(subs(K_p_PM_high_eq,w,w_list(k)));
%      K_i_PM_high_list(k) = eval(subs(K_i_PM_high_eq,w,w_list(k)));
     K_p_list(k) = (10^0*(10^0)^(19/20)*(-(a_0*(b_0+(-b_2+b_1*t_f)*w_list(k)^2)...
    +w_list(k)^2*(-b_0*(1+a_1*t_f)+(b_2-b_1*t_f)*w_list(k)^2+a_1*(b_1+b_2*t_f*w_list(k)^2)))...
    *cos(w_list(k)*T)+w_list(k)*(-(a_0-w_list(k)^2)*(b_1-b_0*t_f+b_2*t_f*w_list(k)^2)...
    +a_1*(b_0+(-b_2+b_1*t_f)*w_list(k)^2))*sin(w_list(k)*T)))/...
    (b_0^2+b_1^2*w_list(k)^2-2*b_0*b_2*w_list(k)^2+b_2^2*w_list(k)^4);

     
     
     K_i_list(k) = (10^0*(10^0)^(19/20)*w_list(k)*(w_list(k)*(-(a_0-w_list(k)^2)*(b_1-b_0*t_f+b_2*t_f*w_list(k)^2)...
    +a_1*(b_0+(-b_2+b_1*t_f)*w_list(k)^2))*cos(w_list(k)*T)...
    +(a_0*(b_0+(-b_2+b_1*t_f)*w_list(k)^2)+w_list(k)^2*(-b_0*(1+a_1*t_f)...
    +(b_2-b_1*t_f)*w_list(k)^2+a_1*(b_1+b_2*t_f*w_list(k)^2)))*sin(w_list(k)*T)))/...
    (b_0^2+b_1^2*w_list(k)^2-2*b_0*b_2*w_list(k)^2+b_2^2*w_list(k)^4);


%       if K_p_list(k) >= 0 && K_i_list(k) >= 0
     if K_i_list(k) > 0
          K_p_list_temp(k2) = K_p_list(k);
          K_i_list_temp(k2) = K_i_list(k);
          k2 = k2 + 1;
     end
     
     
     
     K_p_PM_low_list(k) = (cos(pi*PM_low/180)*(-(a_0*(b_0+(-b_2+b_1*t_f)*w_list(k)^2)...
    +w_list(k)^2*(-b_0*(1+a_1*t_f)+(b_2-b_1*t_f)*w_list(k)^2+a_1*...
    (b_1+b_2*t_f*w_list(k)^2)))*cos(w_list(k)*T)+w_list(k)*(-(a_0-w_list(k)^2)*(b_1-...
    b_0*t_f+b_2*t_f*w_list(k)^2)+a_1*(b_0+(-b_2+b_1*t_f)*w_list(k)^2))*...
    sin(w_list(k)*T))+sin(pi*PM_low/180)*(w_list(k)*(-(a_0-w_list(k)^2)*(b_1-...
    b_0*t_f+b_2*t_f*w_list(k)^2)+a_1*(b_0+(-b_2+b_1*t_f)*w_list(k)^2))*...
    cos(w_list(k)*T)+(a_0*(b_0+(-b_2+b_1*t_f)*w_list(k)^2)+w_list(k)^2*...
    (-b_0*(1+a_1*t_f)+(b_2-b_1*t_f)*w_list(k)^2+a_1*(b_1+b_2*t_f*w_list(k)^2)))*...
    sin(w_list(k)*T)))/...
    (b_0^2+b_1^2*w_list(k)^2-2*b_0*b_2*w_list(k)^2+b_2^2*w_list(k)^4);
     
    
    
     K_i_PM_low_list(k) = (w_list(k)*(sin(pi*PM_low/180)*((a_0*(b_0+(-b_2+...
     b_1*t_f)*w_list(k)^2)+w_list(k)^2*(-b_0*(1+a_1*t_f)+(b_2-b_1*t_f)*w_list(k)^2+...
     a_1*(b_1+b_2*t_f*w_list(k)^2)))*cos(w_list(k)*T)-w_list(k)*(-(a_0-w_list(k)^2)*(b_1-b_0*t_f+...
     b_2*t_f*w_list(k)^2)+a_1*(b_0+(-b_2+b_1*t_f)*w_list(k)^2))*sin(w_list(k)*T))+cos(pi*PM_low/180)*...
     (w_list(k)*(-(a_0-w_list(k)^2)*(b_1-b_0*t_f+b_2*t_f*w_list(k)^2)+a_1*(b_0+(-b_2+...
     b_1*t_f)*w_list(k)^2))*cos(w_list(k)*T)+(a_0*(b_0+(-b_2+b_1*t_f)*w_list(k)^2)+...
     w_list(k)^2*(-b_0*(1+a_1*t_f)+(b_2-b_1*t_f)*w_list(k)^2+a_1*(b_1+b_2*t_f*w_list(k)^2)))*...
     sin(w_list(k)*T))))/...
     (b_0^2+b_1^2*w_list(k)^2-2*b_0*b_2*w_list(k)^2+b_2^2*w_list(k)^4);
 
%        if K_p_PM_low_list(k) >= 0 && K_i_PM_low_list(k) >= 0
       if K_i_PM_low_list(k) > 0
          K_p_PM_low_list_temp(k3) = K_p_PM_low_list(k);
          K_i_PM_low_list_temp(k3) = K_i_PM_low_list(k);
          k3 = k3 + 1;
       end
       
     
     K_p_GM_low_list(k) = (10^(-GM_low)*(10^GM_low)^(19/20)*(-(a_0*(b_0+(-b_2+b_1*t_f)*w_list(k)^2)...
    +w_list(k)^2*(-b_0*(1+a_1*t_f)+(b_2-b_1*t_f)*w_list(k)^2+a_1*(b_1+b_2*t_f*w_list(k)^2)))...
    *cos(w_list(k)*T)+w_list(k)*(-(a_0-w_list(k)^2)*(b_1-b_0*t_f+b_2*t_f*w_list(k)^2)...
    +a_1*(b_0+(-b_2+b_1*t_f)*w_list(k)^2))*sin(w_list(k)*T)))/...
    (b_0^2+b_1^2*w_list(k)^2-2*b_0*b_2*w_list(k)^2+b_2^2*w_list(k)^4);

    
     K_i_GM_low_list(k) = (10^(-GM_low)*(10^GM_low)^(19/20)*w_list(k)*(w_list(k)*(-(a_0-w_list(k)^2)*(b_1-b_0*t_f+b_2*t_f*w_list(k)^2)...
    +a_1*(b_0+(-b_2+b_1*t_f)*w_list(k)^2))*cos(w_list(k)*T)...
    +(a_0*(b_0+(-b_2+b_1*t_f)*w_list(k)^2)+w_list(k)^2*(-b_0*(1+a_1*t_f)...
    +(b_2-b_1*t_f)*w_list(k)^2+a_1*(b_1+b_2*t_f*w_list(k)^2)))*sin(w_list(k)*T)))/...
    (b_0^2+b_1^2*w_list(k)^2-2*b_0*b_2*w_list(k)^2+b_2^2*w_list(k)^4);
%       if K_p_GM_low_list(k) >= 0 && K_i_GM_low_list(k) >= 0
       if K_i_GM_low_list(k) > 0
          K_p_GM_low_list_temp(k4) = K_p_GM_low_list(k);
          K_i_GM_low_list_temp(k4) = K_i_GM_low_list(k);
          k4 = k4 + 1;
       end
     
     K_p_GM_high_list(k) = (10^(-GM_high)*(10^GM_high)^(19/20)*(-(a_0*(b_0+(-b_2+b_1*t_f)*w_list(k)^2)...
    +w_list(k)^2*(-b_0*(1+a_1*t_f)+(b_2-b_1*t_f)*w_list(k)^2+a_1*(b_1+b_2*t_f*w_list(k)^2)))...
    *cos(w_list(k)*T)+w_list(k)*(-(a_0-w_list(k)^2)*(b_1-b_0*t_f+b_2*t_f*w_list(k)^2)...
    +a_1*(b_0+(-b_2+b_1*t_f)*w_list(k)^2))*sin(w_list(k)*T)))/...
    (b_0^2+b_1^2*w_list(k)^2-2*b_0*b_2*w_list(k)^2+b_2^2*w_list(k)^4);

    
    K_i_GM_high_list(k) = (10^(-GM_high)*(10^GM_high)^(19/20)*w_list(k)*(w_list(k)*(-(a_0-w_list(k)^2)*(b_1-b_0*t_f+b_2*t_f*w_list(k)^2)...
    +a_1*(b_0+(-b_2+b_1*t_f)*w_list(k)^2))*cos(w_list(k)*T)...
    +(a_0*(b_0+(-b_2+b_1*t_f)*w_list(k)^2)+w_list(k)^2*(-b_0*(1+a_1*t_f)...
    +(b_2-b_1*t_f)*w_list(k)^2+a_1*(b_1+b_2*t_f*w_list(k)^2)))*sin(w_list(k)*T)))/...
    (b_0^2+b_1^2*w_list(k)^2-2*b_0*b_2*w_list(k)^2+b_2^2*w_list(k)^4);

%        if K_p_GM_high_list(k) >= 0 && K_i_GM_high_list(k) >= 0
       if K_i_GM_high_list(k) > 0
          K_p_GM_high_list_temp(k5) = K_p_GM_high_list(k);
          K_i_GM_high_list_temp(k5) = K_i_GM_high_list(k);
        k5 = k5 + 1;
       end
       
    
    K_p_PM_high_list(k) = (cos(pi*PM_high/180)*(-(a_0*(b_0+(-b_2+b_1*t_f)*w_list(k)^2)...
    +w_list(k)^2*(-b_0*(1+a_1*t_f)+(b_2-b_1*t_f)*w_list(k)^2+a_1*...
    (b_1+b_2*t_f*w_list(k)^2)))*cos(w_list(k)*T)+w_list(k)*(-(a_0-w_list(k)^2)*(b_1-...
    b_0*t_f+b_2*t_f*w_list(k)^2)+a_1*(b_0+(-b_2+b_1*t_f)*w_list(k)^2))*...
    sin(w_list(k)*T))+sin(pi*PM_high/180)*(w_list(k)*(-(a_0-w_list(k)^2)*(b_1-...
    b_0*t_f+b_2*t_f*w_list(k)^2)+a_1*(b_0+(-b_2+b_1*t_f)*w_list(k)^2))*...
    cos(w_list(k)*T)+(a_0*(b_0+(-b_2+b_1*t_f)*w_list(k)^2)+w_list(k)^2*...
    (-b_0*(1+a_1*t_f)+(b_2-b_1*t_f)*w_list(k)^2+a_1*(b_1+b_2*t_f*w_list(k)^2)))*...
    sin(w_list(k)*T)))/...
    (b_0^2+b_1^2*w_list(k)^2-2*b_0*b_2*w_list(k)^2+b_2^2*w_list(k)^4);

    
    K_i_PM_high_list(k) = (w_list(k)*(sin(pi*PM_high/180)*((a_0*(b_0+(-b_2+...
     b_1*t_f)*w_list(k)^2)+w_list(k)^2*(-b_0*(1+a_1*t_f)+(b_2-b_1*t_f)*w_list(k)^2+...
     a_1*(b_1+b_2*t_f*w_list(k)^2)))*cos(w_list(k)*T)-w_list(k)*(-(a_0-w_list(k)^2)*(b_1-b_0*t_f+...
     b_2*t_f*w_list(k)^2)+a_1*(b_0+(-b_2+b_1*t_f)*w_list(k)^2))*sin(w_list(k)*T))+cos(pi*PM_high/180)*...
     (w_list(k)*(-(a_0-w_list(k)^2)*(b_1-b_0*t_f+b_2*t_f*w_list(k)^2)+a_1*(b_0+(-b_2+...
     b_1*t_f)*w_list(k)^2))*cos(w_list(k)*T)+(a_0*(b_0+(-b_2+b_1*t_f)*w_list(k)^2)+...
     w_list(k)^2*(-b_0*(1+a_1*t_f)+(b_2-b_1*t_f)*w_list(k)^2+a_1*(b_1+b_2*t_f*w_list(k)^2)))*...
     sin(w_list(k)*T))))/...
     (b_0^2+b_1^2*w_list(k)^2-2*b_0*b_2*w_list(k)^2+b_2^2*w_list(k)^4);
    
%       if K_p_PM_high_list(k) >= 0 && K_i_PM_high_list(k) >= 0
       if K_i_PM_high_list(k) > 0
          K_p_PM_high_list_temp(k6) = K_p_PM_high_list(k);
          K_i_PM_high_list_temp(k6) = K_i_PM_high_list(k);
          k6 = k6 + 1;
       end
end